name: Rails Tests

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    uses: actions/setup-node@v1
    with:
      node-version: '12'

    - run: echo "::set-output name=RUBY_VERSION::$(cat .ruby-version)"
      id: rubyversion

    - uses: eregon/use-ruby-action@master
      with:
        ruby-version: "${{ steps.rubyversion.outputs.RUBY_VERSION }}"

    - uses: actions/cache@v1
      with:
        path: vendor
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install PostgreSQL 11 client
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Build App
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        gem install bundler:2.0.2
        bundle config path vendor/bundle
        bundle config build.sassc --disable-march-tune-native
        if [ ! -e vendor/bundle/.sassc.updated.146 ]; then rm -f vendor/bundle/specifications/sassc-*; touch vendor/bundle/.sassc.updated.146; fi # trigger a rebuild once
        bundle install --path vendor/bundle --jobs 4 --retry 3
        bin/rails db:setup RAILS_ENV=test
    - name: Run Tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        bundle exec rspec

    - name: Migrate DB
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: development
      run: |
        yarn install
        rm db/schema.rb
        bin/rails db:create RAILS_ENV=development
        bin/rails db:migrate RAILS_ENV=development

